name: MobTools
version: 0.1
author: Rifkin
main: dev.rifkin.MobTools.MobTools
api-version: 1.16
website: rifkin.dev
commands:
  mksphere:
    description: makes a particle sphere
    usage: /mksphere <radius> [semisphere?] [force visible?]
  dspheres:
    description: deletes summoned particle spheres
    usage: /cancelspheres
  showspawn:
    description: visualize spawnable spaces
    usage: /showspawn
  bedrocklocate:
    description: locate a 3x3x3 bedrock "cage"
    usage: /locatebedrockcage
