name: MobTools
version: 1.0
author: Rifkin
main: dev.rifkin.MobTools.MobTools
api-version: 1.16
website: rifkin.dev
commands:
  mksphere:
    description: makes a particle sphere
    usage: /mksphere <radius> [semisphere?] [force visible?]
  cancelspheres:
    description: deletes summoned particle spheres
    usage: /cancelspheres [cancel all?]
  showspawn:
    description: visualize spawnable spaces
    usage: /showspawn [fixed light level]
  locatebedrockcage:
    description: locate a 3x3x3 bedrock "cage"
    usage: /locatebedrockcage
